/*1.Uso de Indices de Cobertura*/

--DROP INDEX IX_TBLVENTAS_NOM_PROD ON tblProductos
CREATE INDEX IX_TBLVENTAS_NOM_PROD ON tblProductos (NOM_PROD) INCLUDE(COD_GRUP,COD_LIN,MARCA,COS_PROM_C,PRECIO_VTA) 
WITH  (DROP_EXISTING=ON)
SELECT * FROM tblProductos tp  WHERE tp.NOM_PROD LIKE 'carne%'

